services:
  rules:
    build:
      context: ./rules/
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=31331
      - MODEL_DATE=31/12/2024
      - APP_VERSION=1.0.0
    volumes:
      - shared-data:/data
      - /home/datasets/spotify:/spotify
    command: python /app/fpg.py
  
  ldsapp:
    build:
      context: ./app/
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - shared-data:/data
  
  ldsfront:
    build:
      context: ./front/
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=31337
      - API_URL=http://ldsapp:31331
    ports:
      - "31337:31337"

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge