services:
  rules:
    build:
      context: ./rules/
      dockerfile: Dockerfile
    image: leandro867/playlist-model:0.3
    environment:
      - PATH_DS=./spotify/2023_spotify_ds1.csv
    volumes:
      - shared-data:/data
      # - ./home/datasets/spotify:/spotify
    command: python /app/fpg.py

  ldsapp:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: leandro867/playlist-api:0.2
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=31331
      - MODEL_DATE=31/12/2024
      - APP_VERSION=1.0.0
    ports:
      - "31331:31331"
    volumes:
      - shared-data:/data

  ldsfront:
    build:
      context: ./front/
      dockerfile: Dockerfile
    image: leandro867/playlist-front:0.2
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=31337
      - API_URL=http://ldsapp:31331
    ports:
      - "31337:31337"

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge
