apiVersion: batch/v1
kind: Job
metadata:
  name: rules-job-v02
  namespace: leandrosilva
spec:
  template:
    metadata:
      labels:
        app: leandrosilva-playlist-recommender
    spec:
      containers:
        - name: rules
          image: leandro867/playlist-model:0.3
          env:
          - name: PATH_DS
            value: "./spotify/2023_spotify_ds2.csv"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          ports:
            - containerPort: 31339
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: leandrosilva-pvc
