apiVersion: v1
kind: Service
metadata:
    name: project-pv2-leandrosilva
spec:
  selector:
    app: project-pv2-leandrosilva
  ports:
    - name: rules-port
      protocol: TCP
      port: 31339
      targetPort: 31339
      nodePort: 31339
    - name: ldsapp-port
      protocol: TCP
      port: 31331
      targetPort: 31331
      nodePort: 31331
    - name: ldsfront-port
      protocol: TCP
      port: 31337
      targetPort: 31337
      nodePort: 31337
  type: NodePort
